### ISSUE TITLE
This hosts file was updated on May 12.

### ISSUE THREAD

**Issue by Voltairine-de-Cleyre** [dead-hosts/iVOID.hosts_git_intr0#3]
It's essentially as the title says. Though, additionally, the tests continue to be run on an outdated list from April 7.

**Comment by funilrys** [comment]
HI @Voltairine-de-Cleyre, thanks for reaching out. I added this into my backlog!

**Comment by Voltairine-de-Cleyre** [comment]
Thank-you 🙂
